name: bpl_project_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0  # Downgraded to match compatibility
  webview_flutter_web: ^0.2.3+2
  flag: ^7.0.0
  flutter_inappwebview: ^5.4.3+6
  cupertino_icons: ^1.0.6
  universal_html: ^2.0.4
  get: ^4.6.1
  file_picker: ^5.0.0
  flutter_svg: ^2.0.10+1
  video_player: ^2.4.5
  chewie: ^1.3.4
  animate_do: ^2.0.0
  http: ^1.2.2
  intl: ^0.19.0
  google_fonts: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/240x180/
